### ISSUE TITLE
error: ‘constexpr double std::abs(double)’ conflicts with a previous declaration

### ISSUE THREAD

**Issue by dragoneye65** [goeiecool9999/terminalclock#1]
Don't compile on a Ubuntu 20.04.3 LTS with gcc 9.3.0.
just fyi.  👍 

$ make
g++ -c clock.cpp
In file included from clock.cpp:8:
/usr/include/c++/9/math.h:38:12: error: ‘constexpr double std::abs(double)’ conflicts with a previous declaration
   38 | using std::abs;
      |            ^~~
In file included from clock.cpp:4:
termg.h:15:8: note: previous declaration ‘double abs(double)’
   15 | double abs(double num);
      |        ^~~
make: *** [Makefile:6: clock.o] Error 1

**Comment by goeiecool9999** [comment]
Thanks for checking out my repo. The code here is left to rot.

**Comment by dragoneye65** [comment]
lol, nw.  :-)
